### ISSUE TITLE
On version 4.0 Hebrew characters often display has Hex

### ISSUE THREAD

**Issue by BaalZvuv** [cfinke/RSS-Ticker#64]
Hi,
Thanks for introducing reverse ticker - I remember I asked for this feature long time ago - So I appreciate it.
On the latest release I noticed that often Hebrew characters are being displayed as Hex decimal values. I haven't seen this phenomenon on previous releases.
I haven't tested it but this issue may or may not occur on other languages as well, though I haven't seen this phenomenon on English characters.

I appreciate your work so far - great app!

**Comment by cfinke** [comment]
Fixed in 5c6ca8ae792b6d9ab35dd2ca5f5fc9e8f87d7271

**Comment by BaalZvuv** [comment]
Hi,
Thanks for the update, however, unfortunately, even on 4.1 I still see on some places the same phenomenon, although not as frequent as on 4.0
